
package co.edu.unicartagena.vista;

import javax.swing.*;
import java.awt.event.ActionEvent;
/**
 *
 * @author kevin
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuRestaurante = new javax.swing.JMenu();
        itemAgregarRestaurante = new javax.swing.JMenuItem();
        itemEditarRestaurante = new javax.swing.JMenuItem();
        itemEliminarRestaurante = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        itemAgregarMenus = new javax.swing.JMenuItem();
        itemEditarMenu = new javax.swing.JMenuItem();
        itemEliminarMenus = new javax.swing.JMenuItem();
        itemConsultarMenu = new javax.swing.JMenuItem();
        menuChef = new javax.swing.JMenu();
        itemAgregarChef = new javax.swing.JMenuItem();
        itemEditarChef = new javax.swing.JMenuItem();
        itemEliminarChef = new javax.swing.JMenuItem();
        itemConsultarChef = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("..:: SISTEMA DE GESTION DE RESTAURANTES::..");

        menuRestaurante.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        menuRestaurante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicartagena/icons/Restaurante 16px.png"))); // NOI18N
        menuRestaurante.setText("Restaurante   ");

        itemAgregarRestaurante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicartagena/icons/Agregar 16px.png"))); // NOI18N
        itemAgregarRestaurante.setText("Agregar restaurante...");
        itemAgregarRestaurante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAgregarRestauranteActionPerformed(evt);
            }
        });
        menuRestaurante.add(itemAgregarRestaurante);

        itemEditarRestaurante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicartagena/icons/Editar 16px.png"))); // NOI18N
        itemEditarRestaurante.setText("Editar restaurante...");
        itemEditarRestaurante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEditarRestauranteActionPerformed(evt);
            }
        });
        menuRestaurante.add(itemEditarRestaurante);

        itemEliminarRestaurante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicartagena/icons/Eliminar 16px.png"))); // NOI18N
        itemEliminarRestaurante.setText("Eliminar restaurante...");
        itemEliminarRestaurante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEliminarRestauranteActionPerformed(evt);
            }
        });
        menuRestaurante.add(itemEliminarRestaurante);
        menuRestaurante.add(jSeparator1);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicartagena/icons/ConsultarAlt 16px.png"))); // NOI18N
        jMenu1.setText("Consultar restaurante");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicartagena/icons/Buscar 16px.png"))); // NOI18N
        jMenuItem1.setText("Consultar todos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        menuRestaurante.add(jMenu1);

        jMenuBar1.add(menuRestaurante);

        jMenu2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicartagena/icons/Menu 16px.png"))); // NOI18N
        jMenu2.setText("Menu    ");

        itemAgregarMenus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicartagena/icons/Agregar 16px.png"))); // NOI18N
        itemAgregarMenus.setText("Agregar menus...");
        itemAgregarMenus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAgregarMenusActionPerformed(evt);
            }
        });
        jMenu2.add(itemAgregarMenus);

        itemEditarMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicartagena/icons/Editar 16px.png"))); // NOI18N
        itemEditarMenu.setText("Editar menus...");
        itemEditarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEditarMenuActionPerformed(evt);
            }
        });
        jMenu2.add(itemEditarMenu);

        itemEliminarMenus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicartagena/icons/Eliminar 16px.png"))); // NOI18N
        itemEliminarMenus.setText("Eliminar menus...");
        itemEliminarMenus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEliminarMenusActionPerformed(evt);
            }
        });
        jMenu2.add(itemEliminarMenus);

        itemConsultarMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicartagena/icons/ConsultarAlt 16px.png"))); // NOI18N
        itemConsultarMenu.setText("Consultar menus...");
        itemConsultarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemConsultarMenuActionPerformed(evt);
            }
        });
        jMenu2.add(itemConsultarMenu);

        jMenuBar1.add(jMenu2);

        menuChef.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        menuChef.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicartagena/icons/Chef 16px.png"))); // NOI18N
        menuChef.setText("Chef  ");

        itemAgregarChef.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicartagena/icons/Agregar 16px.png"))); // NOI18N
        itemAgregarChef.setText("Agregar chef...");
        itemAgregarChef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAgregarChefActionPerformed(evt);
            }
        });
        menuChef.add(itemAgregarChef);

        itemEditarChef.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicartagena/icons/Editar 16px.png"))); // NOI18N
        itemEditarChef.setText("Editar chef...");
        itemEditarChef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEditarChefActionPerformed(evt);
            }
        });
        menuChef.add(itemEditarChef);

        itemEliminarChef.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicartagena/icons/Eliminar 16px.png"))); // NOI18N
        itemEliminarChef.setText("Eliminar chef...");
        itemEliminarChef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEliminarChefActionPerformed(evt);
            }
        });
        menuChef.add(itemEliminarChef);

        itemConsultarChef.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicartagena/icons/ConsultarAlt 16px.png"))); // NOI18N
        itemConsultarChef.setText("Consultar chef...");
        itemConsultarChef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemConsultarChefActionPerformed(evt);
            }
        });
        menuChef.add(itemConsultarChef);

        jMenuBar1.add(menuChef);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 888, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 619, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemAgregarRestauranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAgregarRestauranteActionPerformed
        AgregarRestaurante venRes = new AgregarRestaurante(this, true);
        venRes.setLocationRelativeTo(this);
        venRes.setVisible(true);
    }//GEN-LAST:event_itemAgregarRestauranteActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        ConsultarRestaurantes consRes = new ConsultarRestaurantes(this);
        consRes.setLocationRelativeTo(this);
        consRes.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void itemEditarRestauranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEditarRestauranteActionPerformed
        EditarRestaurante ediRes = new EditarRestaurante(this, true);
        ediRes.setLocationRelativeTo(this);
        ediRes.setVisible(true);
    }//GEN-LAST:event_itemEditarRestauranteActionPerformed

    private void itemEliminarRestauranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEliminarRestauranteActionPerformed
        EliminarRestaurante eliRes = new EliminarRestaurante();
        eliRes.setLocationRelativeTo(this);
        eliRes.setVisible(true);
    }//GEN-LAST:event_itemEliminarRestauranteActionPerformed

    private void itemAgregarMenusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAgregarMenusActionPerformed
        AgregarMenu agreMen = new AgregarMenu(this, true);
        agreMen.setLocationRelativeTo(this);
        agreMen.setVisible(true);
    }//GEN-LAST:event_itemAgregarMenusActionPerformed

    private void itemEliminarMenusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEliminarMenusActionPerformed
        EliminarMenu elimiMenu = new EliminarMenu();
        elimiMenu.setLocationRelativeTo(this);
        elimiMenu.setVisible(true);
    }//GEN-LAST:event_itemEliminarMenusActionPerformed

    private void itemEditarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEditarMenuActionPerformed
        EditarMenu editarMenu = new EditarMenu(this, true);
        editarMenu.setLocationRelativeTo(this);
        editarMenu.setVisible(true);
    }//GEN-LAST:event_itemEditarMenuActionPerformed

    private void itemConsultarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemConsultarMenuActionPerformed
        ConsultarMenu consuMenu = new ConsultarMenu(this);
        consuMenu.setLocationRelativeTo(this);
        consuMenu.setVisible(true);
    }//GEN-LAST:event_itemConsultarMenuActionPerformed

    private void itemAgregarChefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAgregarChefActionPerformed
        AgregarChef agreChef = new AgregarChef(this, true);
        agreChef.setLocationRelativeTo(this);
        agreChef.setVisible(true);
    }//GEN-LAST:event_itemAgregarChefActionPerformed

    private void itemEliminarChefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEliminarChefActionPerformed
        EliminarChef elimiChef = new EliminarChef();
        elimiChef.setLocationRelativeTo(this);
        elimiChef.setVisible(true);        
    }//GEN-LAST:event_itemEliminarChefActionPerformed

    private void itemEditarChefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEditarChefActionPerformed
        EditarChef actuChef = new EditarChef(this, true);
        actuChef.setLocationRelativeTo(this);
        actuChef.setVisible(true);
    }//GEN-LAST:event_itemEditarChefActionPerformed

    private void itemConsultarChefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemConsultarChefActionPerformed
        ConsultarChef consuChef = new ConsultarChef(this);
        consuChef.setLocationRelativeTo(this);
        consuChef.setVisible(true);
    }//GEN-LAST:event_itemConsultarChefActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemAgregarChef;
    private javax.swing.JMenuItem itemAgregarMenus;
    private javax.swing.JMenuItem itemAgregarRestaurante;
    private javax.swing.JMenuItem itemConsultarChef;
    private javax.swing.JMenuItem itemConsultarMenu;
    private javax.swing.JMenuItem itemEditarChef;
    private javax.swing.JMenuItem itemEditarMenu;
    private javax.swing.JMenuItem itemEditarRestaurante;
    private javax.swing.JMenuItem itemEliminarChef;
    private javax.swing.JMenuItem itemEliminarMenus;
    private javax.swing.JMenuItem itemEliminarRestaurante;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu menuChef;
    private javax.swing.JMenu menuRestaurante;
    // End of variables declaration//GEN-END:variables
}
